---
- name: 'prep proxmox hosts for automation'
  hosts: 'npproxmox'
  gather_facts: false
  vars:
    packages:
      - 'python-pip'
      - 'python-dev'
      - 'build-essential'

  tasks:
    - name: 'install python-apt so native apt plugins work'
      package:
        name: 'python-apt'
        state: 'present'
    - name: 'remove enterprise repo'
      apt_repository:
        repo: 'deb https://enterprise.proxmox.com/debian/pve stretch pve-enterprise'
        state: 'absent'
    - name: 'repo'
      apt_repository:
        repo: 'deb http://download.proxmox.com/debian/pve stretch pve-no-subscription'
        state: 'present'
    - name: 'Update all packages to the latest version'
      apt:
        upgrade: 'dist'
    - name: 'Install pip packages'
      apt:
        name: "{{ packages }}"
    - name: 'pip update pip'
      pip:
        name: 'pip'
        state: 'latest'
    - name: 'Install dependencies'
      pip:
        name: "{{ item }}"
        state: 'latest'
      loop:
        - setuptools
        - virtualenv
        - proxmoxer
