---

# postgres role from enix (https://galaxy.ansible.com/enix/postgresql) needed by replication
- src: enix.postgresql
# postgres role for replication (https://galaxy.ansible.com/enix/postgresql_replication)
- src: enix.postgresql_replication
# postgresql installation and management
- src: geerlingguy.postgresql
# bootstrap role
- src: robertdebock.bootstrap
# set hostname
- src: anxs.hostname
# create users with sudo and pubkeys
- src: nickjj.user
# set NTP
- src: geerlingguy.ntp
# ansible-ipv6 disable
- src: juju4.ipv6
# role for ufw management
- src: oefenweb.ufw
# role for ssh hardening
- src: diodonfrost.ssh_hardening
# role for nginx hardening
- src: dev-sec.nginx-hardening
