---
#- name: remove unattended updates
#  hosts: npntms
#  gather_facts: false
#  tasks:
#  - name: remove unattended updates
#    raw:  sed -i 's/APT::Periodic::Update-Package-Lists "1"\;/APT::Periodic::Update-Package-Lists "0"\;/' /etc/apt/apt.conf.d/20auto-upgrades

- name: bootstrap
  hosts: npntms
  gather_facts: false
  roles:
    - { role: robertdebock.bootstrap, bootstrap_retries: 30, tags: bootstrap }
    - { role: anxs.hostname, tags: hostname }
    - { role: "nickjj.user", tags: "user", user_name: "adam", user_groups: [ sudo ], user_local_ssh_key_path: "/home/kmonti/npntms/files/adam_id_rsa.pub" }
    - { role: "nickjj.user", tags: "user", user_name: "kamil", user_groups: [ sudo ], user_local_ssh_key_path: "/home/kmonti/.ssh/id_rsa.pub" }
    - { role: geerlingguy.ntp, tags: ntp }
    - { role: ansible-ipv6, tags: ipv6 }


# todo  fail2ban

- name: ufw | Allow http/s incoming port on frontend
  import_playbook: ufw.yml
  tags: ufw

- name: ssh-hardening
  import_playbook: ssh_harden.yml
  tags: sshharden

- name: nginx-hardening
  import_playbook: nginx_harden.yml
  tags: nginxharden

- name: preserve hostname
  hosts: npntms
  tasks:
  - name: set preserve_hostname
    lineinfile:
      dest: /etc/cloud/cloud.cfg
      regexp: '^preserve_hostname'
      line: 'preserve_hostname: true'
      state: present
    tags: hostname

  - name: set password adam
    user:
      name: adam
      password: $6$1FR4d4zj$6LgmXa9yavJbY5iohV5exWrv183QYiE4zcAKCBf239E06yA5S0mKJnuRFipdhadkah.g8vxYMcQarRtiztajne
    tags: user

  - name: set up LVM
    lvol:
      vg: ubuntu-vg
      lv: ubuntu-lv
      size: +100%FREE
    ignore_errors: true
    tags: lvm

  - name: resize
    command: resize2fs /dev/mapper/ubuntu--vg-ubuntu--lv
    tags: lvm

- name: install Postgresql
  hosts: postgresql
  become: yes
  vars_files:
    - vars/npntmsdb2.yml
  roles:
    - geerlingguy.postgresql
  tags: db
