---

- name: set up LVM
  hosts: npntms
  become: True
  tasks:
  - lvol: 
      vg: ubuntu-vg
      lv: ubuntu-lv
      size: 23G
    tags: lvm

- name: apt upgrade
  hosts: npntms
  become: True
  tasks:
   - name: updates a server
     apt: update_cache=yes
   - name: upgrade a server
     apt: upgrade=dist

- name: "Add user"
  hosts: npntms
  become: True

  roles:
    - { role: "nickjj.user", tags: "user", user_name: "adam", user_groups: [ sudo ], user_local_ssh_key_path: "/home/kmonti/npntms/files/adam_id_rsa.pub" }
    - { role: "nickjj.user", tags: "user", user_name: "kamil", user_groups: [ sudo ], user_local_ssh_key_path: "/home/kmonti/.ssh/id_rsa.pub" }

- name: NTP setup
  hosts: npntms
  become: True
  vars: 
    ntp_timezone: Europe/Warsaw
  roles:
    - geerlingguy.ntp
  tags: ntp

- name: install and configure fail2ban
  import_playbook: fail2ban.yml
  tags: fail2ban

- name: ipv6 disable
  import_playbook: ipv6_disable.yml
  tags: ipv6
# frontend
- name: ufw | Allow http/s incoming port on frontend
  hosts: npntmsfront
  become: True
  roles:
    - oefenweb.ufw
  vars:
    ufw_rules:
      - rule: allow
        to_port: 80
        protocol: tcp
      - rule: allow
        to_port: 443
        protocol: tcp
      - rule: allow
        to_port: 4747
        protocol: tcp
      - rule: allow
        to_port: 22
        protocol: tcp
      - rule: allow
        from_ip: 192.99.119.24/28
      - rule: allow
        from_ip: 51.77.198.196/28

- name: ufw | Allow all traffic between hosts and sites
  hosts: npntms:!npntmsfront
  become: True
  roles:
    - oefenweb.ufw
  vars:
    ufw_rules:
      - rule: allow
        from_ip: 192.99.119.24/28
      - rule: allow
        from_ip: 51.77.198.196/28
      - rule: allow
        to_port: 22
        protocol: tcp

- name: install Postgresql
  hosts: postgresql
  become: True
  vars_files:
    - vars/npntmsdb2.yml
  roles:
    - geerlingguy.postgresql
  tags: db

