---

- name: determine if Java is already installed
  shell: which java
  register: oracle_java_task_installed
  changed_when: oracle_java_task_installed.rc != 0
  failed_when: no

- name: set fact oracle_java_installed
  set_fact:
    oracle_java_installed={{ not oracle_java_task_installed.changed }}

- name: determine which Java version is installed
  shell: java -version 2>&1 | head -n 1 | awk '{ print $3 }' | awk -F '"' '{ print $2 }'
  register: oracle_java_task_version
  when: oracle_java_installed
  changed_when: False

- name: set fact oracle_java_installed_version
  set_fact:
    oracle_java_version_installed="{{ oracle_java_task_version.stdout }}"
  when: oracle_java_task_version is defined and oracle_java_task_version.stdout is defined
  changed_when: False


- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include_tasks: redhat.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
